SELECT
    CAST(date as date) as `date`,
    CAST(add_to_cart as int64) as `add_to_cart`,
    CAST(clicks as int64) as `clicks`,
    CAST((comments) as int64) as `comments`,
    CAST((views + clicks) as int64) as `engagements`,
    CAST(impressions as int64) as `impressions`,
    CAST(mobile_app_install as int64) as `installs`,
    CAST(likes as int64) as `likes`,
    CAST(inline_link_clicks as int64) as `link_clicks`,
    CAST(NULL as int64) as `post_click_conversions`,
    CAST(NULL as int64) as `post_view_converiosns`,
    CAST(NULL as int64) as `posts`,
    CAST((purchase) as int64) as `purchase`,
    CAST(complete_registration as int64) as `registrations`,
    CAST(purchase_value as int64) as `revenue`,
    CAST((shares) as int64) as `shares`,
    CAST(spend as int64) as `spend`,
    CAST(purchase as int64) as `total_conversions`,
    CAST((views) as int64) as `views`,
    CAST(ad_id as string) as `ad_id`,
    CAST(adset_id as string) as `adset_id`,
    CAST(campaign_id as string) as `campaign_id`,
    CAST(channel as string) as `channel`,
    CAST(creative_id as string) as `creative_id`,
    CAST(NULL as string) as `placement_id`
FROM {{ ref ('raw_facebook') }}